LLM_MODEL_NAME = "gpt-4o-mini"
LLM_TEMPERATURE = 0
EMBEDDING_MODEL_NAME = "text-embedding-3-large" 
PILOT_MODE = False # Set to True to process only a small sample (e.g., 10 records). Set to False to process the entire dataset.
PILOT_SIZE = 50
PILOT_SEED = 111
BATCH_SAVE_SIZE = 10 # Save progress every N records 
MAX_CONCURRENT_REQUESTS = 10 #  CONCURRENCY CONTROL: Ajusta este número según tu Tier de OpenAI (20-50 es seguro para Tier 1-2)
BATCH_SIZE = 10 